### ISSUE TITLE
程序使用方法请教

### ISSUE THREAD

**Issue by liujiachao** [Mrlk/Python-TiebaSpider#1]
是修改json里面的starturl来指定爬取的贴吧吗？
那json里面的"Referer"又代表什么呢？

**Comment by Mrlk** [comment]
如果你要爬一个叫"CM"的吧  你可以这样
eg:
https://tieba.baidu.com/f?kw=CM

keyword是一个list，支持多关键字
eg:
['keyword_1','keyword_2']
这些关键字都是并列的
